import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.join(__dirname, '..');
const WEB_DIR = path.join(ROOT_DIR, 'web');
const DIST_DIR = path.join(ROOT_DIR, 'dist');

function copyRecursiveSync(src, dest) {
    const exists = fs.existsSync(src);
    const stats = exists && fs.statSync(src);
    const isDirectory = exists && stats.isDirectory();

    if (isDirectory) {
        if (!fs.existsSync(dest)) {
            fs.mkdirSync(dest, { recursive: true });
        }
        fs.readdirSync(src).forEach((childItemName) => {
            // Skip React source files that Vite already compiled
            if (childItemName === 'App.jsx' || childItemName === 'main.jsx' || childItemName === 'index.css' || childItemName === 'components') {
                return;
            }
            copyRecursiveSync(
                path.join(src, childItemName),
                path.join(dest, childItemName)
            );
        });
    } else if (exists) {
        // Don't overwrite dist/index.html generated by Vite
        if (path.relative(WEB_DIR, src) === 'index.html') {
            return;
        }
        const destDir = path.dirname(dest);
        if (!fs.existsSync(destDir)) {
            fs.mkdirSync(destDir, { recursive: true });
        }
        fs.copyFileSync(src, dest);
    }
}

console.log('📦 Copying J2ME emulator static assets to dist/...');
const itemsToCopy = ['freej2me-web.jar', 'init.zip', 'run.html', 'games', 'libjs', 'libmedia', 'libmidi', 'src', 'assets', '_redirects', '_headers'];

itemsToCopy.forEach((item) => {
    const srcPath = path.join(WEB_DIR, item);
    const destPath = path.join(DIST_DIR, item);
    if (fs.existsSync(srcPath)) {
        copyRecursiveSync(srcPath, destPath);
        console.log(`  └─ Copied ${item}`);
    }
});

console.log('✅ Static assets copied successfully!');
